type OfficialSubclassSeed = {
    id: string;
    name: string;
    unlockLevel?: number;
    source?: string;
};

const SOURCE = "Official D&D 5e";

export const OFFICIAL_SUBCLASS_CATALOG: Record<string, OfficialSubclassSeed[]> = {
    artificer: [
        { id: "artificer:alchemist", name: "Alchemist" },
        { id: "artificer:armorer", name: "Armorer" },
        { id: "artificer:artillerist", name: "Artillerist" },
        { id: "artificer:battle-smith", name: "Battle Smith" },
    ],
    barbarian: [
        { id: "barbarian:path-of-the-berserker", name: "Path of the Berserker" },
        { id: "barbarian:path-of-the-ancestral-guardian", name: "Path of the Ancestral Guardian" },
        { id: "barbarian:path-of-the-battlerager", name: "Path of the Battlerager" },
        { id: "barbarian:path-of-the-beast", name: "Path of the Beast" },
        { id: "barbarian:path-of-the-giant", name: "Path of the Giant" },
        { id: "barbarian:path-of-the-storm-herald", name: "Path of the Storm Herald" },
        { id: "barbarian:path-of-the-totem-warrior", name: "Path of the Totem Warrior" },
        { id: "barbarian:path-of-wild-magic", name: "Path of Wild Magic" },
        { id: "barbarian:path-of-the-wild-heart", name: "Path of the Wild Heart" },
        { id: "barbarian:path-of-the-world-tree", name: "Path of the World Tree" },
        { id: "barbarian:path-of-the-zealot", name: "Path of the Zealot" },
    ],
    bard: [
        { id: "bard:college-of-lore", name: "College of Lore" },
        { id: "bard:college-of-creation", name: "College of Creation" },
        { id: "bard:college-of-dance", name: "College of Dance" },
        { id: "bard:college-of-eloquence", name: "College of Eloquence" },
        { id: "bard:college-of-glamour", name: "College of Glamour" },
        { id: "bard:college-of-spirits", name: "College of Spirits" },
        { id: "bard:college-of-swords", name: "College of Swords" },
        { id: "bard:college-of-valor", name: "College of Valor" },
        { id: "bard:college-of-whispers", name: "College of Whispers" },
    ],
    cleric: [
        { id: "cleric:life-domain", name: "Life Domain" },
        { id: "cleric:arcana-domain", name: "Arcana Domain" },
        { id: "cleric:death-domain", name: "Death Domain" },
        { id: "cleric:forge-domain", name: "Forge Domain" },
        { id: "cleric:grave-domain", name: "Grave Domain" },
        { id: "cleric:knowledge-domain", name: "Knowledge Domain" },
        { id: "cleric:light-domain", name: "Light Domain" },
        { id: "cleric:nature-domain", name: "Nature Domain" },
        { id: "cleric:order-domain", name: "Order Domain" },
        { id: "cleric:peace-domain", name: "Peace Domain" },
        { id: "cleric:tempest-domain", name: "Tempest Domain" },
        { id: "cleric:trickery-domain", name: "Trickery Domain" },
        { id: "cleric:twilight-domain", name: "Twilight Domain" },
        { id: "cleric:war-domain", name: "War Domain" },
    ],
    druid: [
        { id: "druid:circle-of-the-land", name: "Circle of the Land" },
        { id: "druid:circle-of-the-moon", name: "Circle of the Moon" },
        { id: "druid:circle-of-dreams", name: "Circle of Dreams" },
        { id: "druid:circle-of-the-shepherd", name: "Circle of the Shepherd" },
        { id: "druid:circle-of-spores", name: "Circle of Spores" },
        { id: "druid:circle-of-stars", name: "Circle of Stars" },
        { id: "druid:circle-of-wildfire", name: "Circle of Wildfire" },
        { id: "druid:circle-of-the-sea", name: "Circle of the Sea" },
    ],
    fighter: [
        { id: "fighter:champion", name: "Champion" },
        { id: "fighter:battle-master", name: "Battle Master" },
        { id: "fighter:eldritch-knight", name: "Eldritch Knight" },
        { id: "fighter:arcane-archer", name: "Arcane Archer" },
        { id: "fighter:banneret", name: "Banneret" },
        { id: "fighter:cavalier", name: "Cavalier" },
        { id: "fighter:echo-knight", name: "Echo Knight" },
        { id: "fighter:psi-warrior", name: "Psi Warrior" },
        { id: "fighter:rune-knight", name: "Rune Knight" },
        { id: "fighter:samurai", name: "Samurai" },
    ],
    monk: [
        { id: "monk:warrior-of-the-open-hand", name: "Warrior of the Open Hand" },
        { id: "monk:way-of-mercy", name: "Way of Mercy" },
        { id: "monk:warrior-of-the-elements", name: "Warrior of the Elements" },
        { id: "monk:warrior-of-shadow", name: "Warrior of Shadow" },
        { id: "monk:way-of-the-astral-self", name: "Way of the Astral Self" },
        { id: "monk:way-of-the-ascendant-dragon", name: "Way of the Ascendant Dragon" },
        { id: "monk:way-of-the-drunken-master", name: "Way of the Drunken Master" },
        { id: "monk:way-of-the-kensei", name: "Way of the Kensei" },
        { id: "monk:way-of-the-long-death", name: "Way of the Long Death" },
        { id: "monk:way-of-the-sun-soul", name: "Way of the Sun Soul" },
    ],
    paladin: [
        { id: "paladin:oath-of-devotion", name: "Oath of Devotion" },
        { id: "paladin:oath-of-the-ancients", name: "Oath of the Ancients" },
        { id: "paladin:oath-of-glory", name: "Oath of Glory" },
        { id: "paladin:oath-of-vengeance", name: "Oath of Vengeance" },
        { id: "paladin:oath-of-conquest", name: "Oath of Conquest" },
        { id: "paladin:oath-of-the-crown", name: "Oath of the Crown" },
        { id: "paladin:oath-of-redemption", name: "Oath of Redemption" },
        { id: "paladin:oath-of-the-watchers", name: "Oath of the Watchers" },
        { id: "paladin:oathbreaker", name: "Oathbreaker" },
    ],
    ranger: [
        { id: "ranger:hunter", name: "Hunter" },
        { id: "ranger:beast-master", name: "Beast Master" },
        { id: "ranger:drakewarden", name: "Drakewarden" },
        { id: "ranger:fey-wanderer", name: "Fey Wanderer" },
        { id: "ranger:gloom-stalker", name: "Gloom Stalker" },
        { id: "ranger:horizon-walker", name: "Horizon Walker" },
        { id: "ranger:monster-slayer", name: "Monster Slayer" },
        { id: "ranger:swarmkeeper", name: "Swarmkeeper" },
    ],
    rogue: [
        { id: "rogue:thief", name: "Thief" },
        { id: "rogue:assassin", name: "Assassin" },
        { id: "rogue:arcane-trickster", name: "Arcane Trickster" },
        { id: "rogue:inquisitive", name: "Inquisitive" },
        { id: "rogue:mastermind", name: "Mastermind" },
        { id: "rogue:phantom", name: "Phantom" },
        { id: "rogue:scout", name: "Scout" },
        { id: "rogue:soulknife", name: "Soulknife" },
        { id: "rogue:swashbuckler", name: "Swashbuckler" },
    ],
    sorcerer: [
        { id: "sorcerer:draconic-sorcery", name: "Draconic Sorcery" },
        { id: "sorcerer:aberrant-sorcery", name: "Aberrant Sorcery" },
        { id: "sorcerer:clockwork-sorcery", name: "Clockwork Sorcery" },
        { id: "sorcerer:wild-magic-sorcery", name: "Wild Magic Sorcery" },
        { id: "sorcerer:divine-soul", name: "Divine Soul" },
        { id: "sorcerer:lunar-sorcery", name: "Lunar Sorcery" },
        { id: "sorcerer:shadow-magic", name: "Shadow Magic" },
        { id: "sorcerer:storm-sorcery", name: "Storm Sorcery" },
    ],
    warlock: [
        { id: "warlock:fiend-patron", name: "Fiend Patron" },
        { id: "warlock:archfey-patron", name: "Archfey Patron" },
        { id: "warlock:great-old-one-patron", name: "Great Old One Patron" },
        { id: "warlock:celestial-patron", name: "Celestial Patron" },
        { id: "warlock:fathomless-patron", name: "Fathomless Patron" },
        { id: "warlock:genie-patron", name: "Genie Patron" },
        { id: "warlock:hexblade-patron", name: "Hexblade Patron" },
        { id: "warlock:undead-patron", name: "Undead Patron" },
        { id: "warlock:undying-patron", name: "Undying Patron" },
    ],
    wizard: [
        { id: "wizard:evoker", name: "Evoker" },
        { id: "wizard:abjurer", name: "Abjurer" },
        { id: "wizard:bladesinging", name: "Bladesinging" },
        { id: "wizard:chronurgy-magic", name: "Chronurgy Magic" },
        { id: "wizard:conjurer", name: "Conjurer" },
        { id: "wizard:diviner", name: "Diviner" },
        { id: "wizard:enchanter", name: "Enchanter" },
        { id: "wizard:graviturgy-magic", name: "Graviturgy Magic" },
        { id: "wizard:illusionist", name: "Illusionist" },
        { id: "wizard:necromancer", name: "Necromancer" },
        { id: "wizard:order-of-scribes", name: "Order of Scribes" },
        { id: "wizard:transmuter", name: "Transmuter" },
        { id: "wizard:war-magic", name: "War Magic" },
    ],
};

for (const classId of Object.keys(OFFICIAL_SUBCLASS_CATALOG)) {
    OFFICIAL_SUBCLASS_CATALOG[classId] = OFFICIAL_SUBCLASS_CATALOG[classId].map(
        (subclass) => ({
            unlockLevel: 3,
            source: SOURCE,
            ...subclass,
        })
    );
}

