export const OFFICIAL_SUBCLASS_NAMES_ES: Record<string, string> = {
  "artificer:alchemist": "Alquimista",
  "artificer:armorer": "Armero",
  "artificer:artillerist": "Artillero",
  "artificer:battle-smith": "Herrero de Batalla",
  "barbarian:path-of-the-berserker": "El Camino del Berserker",
  "barbarian:path-of-the-ancestral-guardian": "Camino del Guardian Ancestral",
  "barbarian:path-of-the-battlerager": "El Camino del Guerrero",
  "barbarian:path-of-the-beast": "Camino de la Bestia",
  "barbarian:path-of-the-giant": "Camino del Gigante",
  "barbarian:path-of-the-storm-herald": "El Camino del Heraldo de la Tormenta",
  "barbarian:path-of-the-totem-warrior": "El Camino del Guerrero Totem",
  "barbarian:path-of-wild-magic": "Camino de la Magia Salvaje",
  "barbarian:path-of-the-wild-heart": "Camino del Corazon Salvaje",
  "barbarian:path-of-the-world-tree": "Camino del Arbol del Mundo",
  "barbarian:path-of-the-zealot": "El Camino del Fanatico",
  "bard:college-of-lore": "Colegio del Saber",
  "bard:college-of-creation": "Colegio de Creacion",
  "bard:college-of-dance": "Colegio de Danza",
  "bard:college-of-eloquence": "Colegio de Elocuencia",
  "bard:college-of-glamour": "Colegio de Glamour",
  "bard:college-of-spirits": "Colegio de Espiritus",
  "bard:college-of-swords": "Colegio de Espadas",
  "bard:college-of-valor": "Colegio de Valor",
  "bard:college-of-whispers": "Colegio de Susurros",
  "cleric:life-domain": "Dominio de la Vida",
  "cleric:arcana-domain": "Dominio Arcano",
  "cleric:death-domain": "Dominio de la Muerte",
  "cleric:forge-domain": "Dominio de Forja",
  "cleric:grave-domain": "Dominio de la Tumba",
  "cleric:knowledge-domain": "Dominio del Conocimiento",
  "cleric:light-domain": "Dominio de la Luz",
  "cleric:nature-domain": "Dominio de la Naturaleza",
  "cleric:order-domain": "Dominio del Orden",
  "cleric:peace-domain": "Dominio de la Paz",
  "cleric:tempest-domain": "Dominio de la Tempestad",
  "cleric:trickery-domain": "Dominio de Engano",
  "cleric:twilight-domain": "Dominio Crepuscular",
  "cleric:war-domain": "Dominio de la Guerra",
  "druid:circle-of-the-land": "Circulo de la Tierra",
  "druid:circle-of-the-moon": "Circulo de la Luna",
  "druid:circle-of-dreams": "Circulo de Suenos",
  "druid:circle-of-the-shepherd": "Circulo del Pastor",
  "druid:circle-of-spores": "Circulo de Esporas",
  "druid:circle-of-stars": "Circulo de Estrellas",
  "druid:circle-of-wildfire": "Circulo de Incendios Forestales",
  "druid:circle-of-the-sea": "Circulo del Mar",
  "fighter:champion": "Campeon",
  "fighter:battle-master": "Maestro de Batalla",
  "fighter:eldritch-knight": "Caballero Sobrenatural",
  "fighter:arcane-archer": "Arquero Arcano",
  "fighter:banneret": "Abanderado",
  "fighter:cavalier": "Caballero",
  "fighter:echo-knight": "Caballero Eco",
  "fighter:psi-warrior": "Guerrero Psiquico",
  "fighter:rune-knight": "Caballero Runa",
  "fighter:samurai": "Samurai",
  "monk:warrior-of-the-open-hand": "Guerrero de la Mano Abierta",
  "monk:way-of-mercy": "Camino de la Misericordia",
  "monk:warrior-of-the-elements": "Guerrero de los Elementos",
  "monk:warrior-of-shadow": "Guerrero de la Sombra",
  "monk:way-of-the-astral-self": "Camino del Ser Astral",
  "monk:way-of-the-ascendant-dragon": "Camino del Dragon Ascendente",
  "monk:way-of-the-drunken-master": "Camino del Maestro Borracho",
  "monk:way-of-the-kensei": "Camino del Kensei",
  "monk:way-of-the-long-death": "Camino de la Larga Muerte",
  "monk:way-of-the-sun-soul": "Camino del Alma Solar",
  "paladin:oath-of-devotion": "Juramento de Devocion",
  "paladin:oath-of-the-ancients": "Juramento de los Antiguos",
  "paladin:oath-of-glory": "Juramento de Gloria",
  "paladin:oath-of-vengeance": "Juramento de Venganza",
  "paladin:oath-of-conquest": "Juramento de Conquista",
  "paladin:oath-of-the-crown": "Juramento de la Corona",
  "paladin:oath-of-redemption": "Juramento de Redencion",
  "paladin:oath-of-the-watchers": "Juramento de los Vigilantes",
  "paladin:oathbreaker": "Rompejuramentos",
  "ranger:hunter": "Cazador",
  "ranger:beast-master": "Maestro de las Bestias",
  "ranger:drakewarden": "Guardian del Dracon",
  "ranger:fey-wanderer": "Errante Feerico",
  "ranger:gloom-stalker": "Acechador Sombrio",
  "ranger:horizon-walker": "Caminante del Horizonte",
  "ranger:monster-slayer": "Asesino de Monstruos",
  "ranger:swarmkeeper": "Guardian de Enjambres",
  "rogue:thief": "Ladron",
  "rogue:assassin": "Asesino",
  "rogue:arcane-trickster": "Embaucador Arcano",
  "rogue:inquisitive": "Inquisitivo",
  "rogue:mastermind": "Mente Maestra",
  "rogue:phantom": "Fantasma",
  "rogue:scout": "Explorador",
  "rogue:soulknife": "Cuchilla del Alma",
  "rogue:swashbuckler": "Bravucon",
  "sorcerer:draconic-sorcery": "Hechiceria Draconica",
  "sorcerer:aberrant-sorcery": "Hechiceria Aberrante",
  "sorcerer:clockwork-sorcery": "Hechiceria Mecanica",
  "sorcerer:wild-magic-sorcery": "Hechiceria Magica Salvaje",
  "sorcerer:divine-soul": "Alma Divina",
  "sorcerer:lunar-sorcery": "Hechiceria Lunar",
  "sorcerer:shadow-magic": "Magia de las Sombras",
  "sorcerer:storm-sorcery": "Hechiceria de Tormenta",
  "warlock:fiend-patron": "Patron Infernal",
  "warlock:archfey-patron": "Patron Archifeerico",
  "warlock:great-old-one-patron": "Patron del Gran Primigenio",
  "warlock:celestial-patron": "Patron Celestial",
  "warlock:fathomless-patron": "Patron Insondable",
  "warlock:genie-patron": "Patron del Genio",
  "warlock:hexblade-patron": "Patron de la Hoja Maldita",
  "warlock:undead-patron": "Patron No-muerto",
  "warlock:undying-patron": "Patron Eterno",
  "wizard:evoker": "Evocador",
  "wizard:abjurer": "Abjurador",
  "wizard:bladesinging": "Canto de Espadas",
  "wizard:chronurgy-magic": "Magia de Cronurgia",
  "wizard:conjurer": "Conjurador",
  "wizard:diviner": "Adivino",
  "wizard:enchanter": "Encantador",
  "wizard:graviturgy-magic": "Magia de Graviturgia",
  "wizard:illusionist": "Ilusionista",
  "wizard:necromancer": "Nigromante",
  "wizard:order-of-scribes": "Orden de los Escribas",
  "wizard:transmuter": "Transmutador",
  "wizard:war-magic": "Magia de Guerra",
};
